blank_issues_enabled: true
contact_links:
  - name: Sixbit Core Security Policy
    url: https://github.com.sixbit.sixbit/blob/master/SECURITY.md
    about: View security policy
  - name: Sixbit Core Developers
    url: https://6bit.dev
    about: Sixbit Core homepage
