#ifndef SIXBIT_CHAINPARAMSSEEDS_H
#define SIXBIT_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the sixbit network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */

static const uint8_t chainparams_seed_main[] = {};

#endif // SIXBIT_CHAINPARAMSSEEDS_H
