description "Sixbit Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env SIXBITD_BIN="/usr/bin/sixbitd"
env SIXBITD_USER="sixbit"
env SIXBITD_GROUP="sixbit"
env SIXBITD_PIDDIR="/var/run/sixbitd"
env SIXBITD_PIDFILE="/var/run/sixbitd/sixbitd.pid"
env SIXBITD_CONFIGFILE="/etc/sixbit/sixbit.conf"
env SIXBITD_DATADIR="/var/lib/sixbitd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    if ! grep -qsE '^(rpcpassword|rpcauth)=' "$SIXBITD_CONFIGFILE"; then
        echo "ERROR: You must set a secure RPC authentication option to run sixbitd."
        echo "The setting must appear in $SIXBITD_CONFIGFILE"
        echo
        echo "It is recommended that you also set alertnotify so you are"
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"sixbit Alert\" admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$SIXBITD_PIDDIR"
    chmod 0755 "$SIXBITD_PIDDIR"
    chown $SIXBITD_USER:$SIXBITD_GROUP "$SIXBITD_PIDDIR"

    mkdir -p "$SIXBITD_DATADIR"
    chmod 0750 "$SIXBITD_DATADIR"
    chown $SIXBITD_USER:$SIXBITD_GROUP "$SIXBITD_DATADIR"

    chown $SIXBITD_USER:$SIXBITD_GROUP "$SIXBITD_CONFIGFILE"
    chmod 0660 "$SIXBITD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$SIXBITD_PIDFILE" \
    --chuid $SIXBITD_USER:$SIXBITD_GROUP \
    --exec "$SIXBITD_BIN" \
    -- \
    -pid="$SIXBITD_PIDFILE" \
    -conf="$SIXBITD_CONFIGFILE" \
    -datadir="$SIXBITD_DATADIR" \
    -disablewallet \
    -daemon